version: "3.8"
services:
  nginx:
    depends_on:
      - server
      - app
    restart: always
    build: ./nginx
    ports:
      - "3050:80"

  server:
    build: ./server
    container_name: mtg-metasyn-server
    restart: always
    environment:
      - APP_NAME=MTG-MetaSyn-Server
    ports:
      - 8080:5000

  app:
    build: ./app
    container_name: mtg-metasyn-app
    volumes:
      - /app/node_modules
      - ./app:/src
    ports:
      - 8081:5001
    environment:
      - CHOKIDAR_USEPOLLING=true
