version: "3.8"
services:
  server:
    build: ./server
    container_name: mtg-metasyn-server
    restart: always
    environment:
      - APP_NAME=MTG-MetaSyn-Server
    ports:
      - 5000:5000
    volumes:
      - /server

  app:
    build: ./app
    container_name: mtg-metasyn-app
    volumes:
      - /app/node_modules
      - ./app:/src
    ports:
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true
