version: "3.7"

services:
  server:
    build: ./server
    container_name: mtg-metasyn-server
    restart: always
    environment:
      - APP_NAME=MTG-MetaSyn-Server
    ports:
      - 8080:5000
  app:
    build: ./app
    container_name: mtg-metasyn-app
    volumes:
      - ".:/app"
      - "/node_modules"
    ports:
      - 3001:1234
    environment:
      - CHOKIDAR_USEPOLLING=true
